### ISSUE TITLE
Audio incompatibilities between server and client

### ISSUE THREAD

**Issue by ashjack** [ashjack/Sim-U-Kraft-Reloaded#14]
http://pastebin.com/tLdb02ve

**Comment by ashjack** [comment]
Possibly fixed in 1.0.3b. Will re-open if the issue arises again.

**Comment by Kyle42Christian** [comment]
Requesting Reopen. Mods current through Jan 18' 
[crash-2018-01-25_18.19.28-client.txt](https://github.com/ashjack/Sim-U-Kraft-Reloaded/files/1669369/crash-2018-01-25_18.19.28-client.txt)
