### ISSUE TITLE
Server shutdown in building gui

### ISSUE THREAD

**Issue by Mem4mc** [ashjack/Sim-U-Kraft-Reloaded#16]
Using vanilla minecraft with forge 1291 and sUk v101c on a single player world (seed: simukrafttestworld).
clicking on 'done' after selecting small house to build will cause a server 
shutdown and screen will go to looking for Lan.
There is no crash report generated within the instances folders.

Pastebin pages,
Forgelog:
vCvkS9mJ
3iqLzqn3
Panal output:
y8eSY52s

**Comment by ashjack** [comment]
Fixed in 1.0.1d
