### ISSUE TITLE
Crashing.  Not sure what is contributing

### ISSUE THREAD

**Issue by Legend1977** [ashjack/Sim-U-Kraft-Reloaded#20]
I've only just started my village.  I've got 1 house, a lumbermill, and am in the middle of building a 2nd house.  Only 2 villagers.

I did go into the Jar file and remove the sounds ".obb" files to see if that helped.  No difference.
I tried with Forge 10.13.0.1180 for 1.7.10 and also Forge 10.13.2.1291 for 1.7.10.  I also had Liteloader so I could use Zan's Minimap but I've also tried without using that.

Here is my Pastebin
http://pastebin.com/raw.php?i=qKx8MbuC

**Comment by ashjack** [comment]
Duplicate issue. See here: https://github.com/ashjack/Sim-U-Kraft-Reloaded/issues/14
