### ISSUE TITLE
Sim-U-Burgers building

### ISSUE THREAD

**Issue by Mem4mc** [ashjack/Sim-U-Kraft-Reloaded#23]
version 1.0.2a
possible typos in building text file and incomplete construction.
double semicolon between W and Y in resource list. Stairways replaced by other symbols not listed.

Using:
Forge 1291
Optifine HD_B5
NEI 1.0.3.74 (with CCC)

**Comment by xcb567** [comment]
The building textfile got a couple of 180:* BlockIDs
Those really look funny when running with FTBs Direwolf20 modpack 
![layer 01](https://cloud.githubusercontent.com/assets/2505192/6310714/c22bc756-b959-11e4-805c-7cc007b6885a.png)

**Comment by ashjack** [comment]
Fixed semicolon typo. There are no 180 block ids in the file anymore. Please do as you were instructed on in the thread and replace the simukraft folder you already have with the one from the latest version.
