### ISSUE TITLE
Builder is only building on one side of build box

### ISSUE THREAD

**Issue by sim181** [ashjack/Sim-U-Kraft-Reloaded#27]
No matter the direction I face when placing the box or the direction I'm facing when right clicking the builder always picks the same side.

List of mods running:
All current to forge build for sim-u-kraft

Sim-U-Kraft Realoaded by AshJack
WAILA by ProfMobius
CodeChickenCore & NotEnoughItems by chicken_bones
Backpacks by Eydamos
Damage Indicators
Optifine
Furniture Mod by MrCrayfish

**Comment by sim181** [comment]
Pastebin of logs
Latest : 
http://pastebin.com/zH8057FZ
fml latest part 1:
http://pastebin.com/ufspCrSK 
fml latest part 2:
http://pastebin.com/kR9rtdRL

**Comment by ashjack** [comment]
Issue on your side. Nothing helpful in the logs.
