### ISSUE TITLE
Issue with Normal difficulty.

### ISSUE THREAD

**Issue by noswanson1982** [ashjack/Sim-U-Kraft-Reloaded#28]
We were sure we selected the "Normal" difficulty, but it is asking for all of the building materials as if we were playing Hardcore.  Is there a way to confirm whether we are in Hardcore, and is there a way to change it without actually restarting the map over again?

**Comment by ashjack** [comment]
Is an issue on your side. You must have clicked hardcore. To change the gamemode open .minecraft/saves/yourWorld/simukraft/settings.sk2 with notepad or any text editor.

Once in the file change the gamemode setting to 0
