### ISSUE TITLE
Random crash when building

### ISSUE THREAD

**Issue by sim181** [ashjack/Sim-U-Kraft-Reloaded#29]
When building I get a server loop crash. This pastebin is with mods however its the same problems without them.

http://pastebin.com/EWzQ25rb

**Comment by Mem4mc** [comment]
I think AshJack initially began his rebuild with forge 1277 and latest recommended is 1291. That may be one point to try.

**Comment by sim181** [comment]
Worked for about 20 mins, but crashed when building is still present when using forge 1291

http://pastebin.com/k7bSPHEi

**Comment by sim181** [comment]
Forgot to add, it only happens when the builder has to remove blocks to build.

**Comment by NeonEnderman19** [comment]
hey i have a problem i downloaded the mod and everything is right untill i try to craft a house none of the buildings show up

**Comment by NeonEnderman19** [comment]
i have forge 1.7.10 but nothing

**Comment by FangTheHusky** [comment]
Has this issue been fixed? I've tried both 1.0.3a & b and get the same crash.
