### ISSUE TITLE
Copy the location wrong house

### ISSUE THREAD

**Issue by simonlii** [ashjack/Sim-U-Kraft-Reloaded#32]
Copy the location wrong house

Copy ago:
![2015-03-21_07 35 16](https://cloud.githubusercontent.com/assets/11499748/6762548/52f5ac62-cf9d-11e4-8977-7277ab24162b.png)

Copied:
![2015-03-21_07 35 37](https://cloud.githubusercontent.com/assets/11499748/6762551/5ef39d76-cf9d-11e4-9e94-45faacf65153.png)

**Comment by ashjack** [comment]
Fixed in 1.0.3
