### ISSUE TITLE
Houses 

### ISSUE THREAD

**Issue by marcusemilia** [ashjack/Sim-U-Kraft-Reloaded#33]
The Houses won't load
![2015-03-22_13 07 27](https://cloud.githubusercontent.com/assets/11597512/6769459/7842baa8-d094-11e4-9d2a-e7ecf2f3134e.png)

**Comment by ashjack** [comment]
Please make sure the issue is not on your behalf before posting an issue. Please refer to the readme that came with the download to know how to install the mod.

**Comment by marcusemilia** [comment]
That didn't work either
