### ISSUE TITLE
SuK selection GUI issues on version 1.0.3

### ISSUE THREAD

**Issue by Mem4mc** [ashjack/Sim-U-Kraft-Reloaded#34]
Unable to start Normal mode + Creative/Hard mode abnormalities

When SuK selection GUI appears and Normal mode is selected, game freezes with GUI still presented and javaw pegs 99% cpu usage.
I allowed it 5 minutes to complete any processing before having to kill Minecraft.

When Suk selection GUI appears and Creative or Hard mode is selected, GUI closes but any block punched disappears (as if in vanilla creative game-mode)
Output log shows SuK reloaded in correct mode and building loaded.

Selecting to Not run SuK in this world works correctly.

I am seeing one SuK specific exception at end of spawn area. (aprox. line 350)

Output log: pastebin nghC0h62

If other info needed, please let me know.

**Comment by ashjack** [comment]
While I understand this to be a problem, the log simply doesn't provide enough information. This is not your fault, but the only information logged was which number thread the exception occurred in, and that doesn't help me.

**Comment by Mem4mc** [comment]
Would it be worth getting the full fml-client-latest.log to you (very large)?
I will be going through it carefully myself.

**Comment by ashjack** [comment]
It may be, however, I am now experiencing the same issue (never experienced it before building 1.0.3) so I should be able to look through it myself.

**Comment by Mem4mc** [comment]
If you need an alternative/secondary log from a low end system for comparison, just let me know.

**Comment by ashjack** [comment]
Fixed in 1.0.3a
