### ISSUE TITLE
In the game no any population. Sim-U-Kraft-Reloaded 1.0.3

### ISSUE THREAD

**Issue by simonlii** [ashjack/Sim-U-Kraft-Reloaded#36]
In the game no any population. So I can not play the game.

Whether in Creavite or Normal.

In the Creavite mode:
![2015-03-29_12 51 57](https://cloud.githubusercontent.com/assets/11499748/6884153/11dd7f9e-d613-11e4-868f-157b0b16a65b.png)
In the Normal mode:
Game crashes

**Comment by ashjack** [comment]
Duplicate Issue
