### ISSUE TITLE
Sim U kraft reloaded 1.0.2a Crashes

### ISSUE THREAD

**Issue by Mewami** [ashjack/Sim-U-Kraft-Reloaded#37]
hello, 
I'm sorry to tell you that after a while playing the Sim U kraft reloaded 1.0.2a the game crashes after a short time at anytime. I can't figure out why .....

I'm using additional only the Crayfish furniture mod 

greetings from Germany
Mewa

**Comment by ashjack** [comment]
Please provide a log of the crash, otherwise I can't help you.

**Comment by Mewami** [comment]
Problem is for a while fixed if I fire all employees....
I show you the log when i copied it ;)
I have to say I like the mod very much and I am impressed you answered that quick !!! thank you for keep it rollin :)

**Comment by Mewami** [comment]
Thanks for your work
---- Minecraft Crash Report ----
// You're mean.

Time: 29.03.15 11:16
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at ashjack.simukraftreloaded.core.registry.SimukraftReloaded.getSavesDataFolder(SimukraftReloaded.java:188)
	at ashjack.simukraftreloaded.core.building.Building.loadAllBuildings(Building.java:993)
	at ashjack.simukraftreloaded.client.Gui.blocks.GuiControlBox.<init>(GuiControlBox.java:50)
	at ashjack.simukraftreloaded.blocks.BlockControlBox.func_149727_a(BlockControlBox.java:105)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1436)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1942)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ashjack.simukraftreloaded.core.registry.SimukraftReloaded.getSavesDataFolder(SimukraftReloaded.java:188)
	at ashjack.simukraftreloaded.core.building.Building.loadAllBuildings(Building.java:993)
	at ashjack.simukraftreloaded.client.Gui.blocks.GuiControlBox.<init>(GuiControlBox.java:50)
	at ashjack.simukraftreloaded.blocks.BlockControlBox.func_149727_a(BlockControlBox.java:105)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1436)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['Mewani'/119189, l='MpServer', x=222,07, y=72,12, z=262,78], EntityOtherPlayerMP['Gigha'/321, l='MpServer', x=225,66, y=70,00, z=263,66]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (232,64,248), Chunk: (at 8,4,8 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 47791 game time, 51558 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 84 total; [EntityZombie['Zombie'/136960, l='MpServer', x=288,50, y=29,00, z=218,50], EntitySkeleton['Skeleton'/136961, l='MpServer', x=288,50, y=29,00, z=220,50], EntityClientPlayerMP['Mewani'/119189, l='MpServer', x=222,07, y=72,12, z=262,78], EntitySheep['Sheep'/127517, l='MpServer', x=207,09, y=70,00, z=255,09], EntitySheep['Sheep'/127519, l='MpServer', x=211,28, y=70,00, z=256,97], EntitySheep['Sheep'/127518, l='MpServer', x=207,69, y=70,00, z=260,78], EntitySheep['Sheep'/127520, l='MpServer', x=208,44, y=70,00, z=255,09], EntitySkeleton['Skeleton'/133408, l='MpServer', x=263,50, y=28,00, z=230,50], EntityPig['Pig'/40, l='MpServer', x=143,63, y=70,00, z=253,50], EntityPig['Pig'/41, l='MpServer', x=148,31, y=70,00, z=262,50], EntitySkeleton['Skeleton'/133419, l='MpServer', x=266,06, y=29,00, z=221,50], EntityPig['Pig'/42, l='MpServer', x=153,06, y=69,00, z=252,06], EntityPig['Pig'/43, l='MpServer', x=157,03, y=69,00, z=250,97], EntityPig['Pig'/44, l='MpServer', x=150,69, y=70,00, z=249,31], EntityPig['Pig'/46, l='MpServer', x=153,66, y=69,00, z=267,13], EntityPig['Pig'/47, l='MpServer', x=152,50, y=72,00, z=281,69], EntityPig['Pig'/48, l='MpServer', x=151,91, y=71,00, z=323,13], EntityPig['Pig'/49, l='MpServer', x=157,84, y=69,00, z=257,22], EntityPig['Pig'/51, l='MpServer', x=152,13, y=71,00, z=326,28], EntityOtherPlayerMP['Gigha'/321, l='MpServer', x=225,66, y=70,00, z=263,66], EntityBat['Bat'/135478, l='MpServer', x=248,75, y=22,70, z=235,88], EntityBat['Bat'/135477, l='MpServer', x=234,50, y=24,92, z=225,31], EntityItem['item.tile.sapling.oak'/136767, l='MpServer', x=199,47, y=70,13, z=257,38], EntitySheep['Sheep'/62, l='MpServer', x=175,81, y=68,00, z=189,50], EntitySheep['Sheep'/64, l='MpServer', x=170,50, y=67,00, z=190,50], EntityOtherPlayerMP['Gigha'/321, l='MpServer', x=225,66, y=70,00, z=263,66], EntityPig['Pig'/65, l='MpServer', x=171,91, y=71,00, z=311,22], EntityPig['Pig'/66, l='MpServer', x=200,13, y=69,00, z=313,38], EntityPig['Pig'/67, l='MpServer', x=176,09, y=71,00, z=315,06], EntityPig['Pig'/68, l='MpServer', x=154,91, y=72,00, z=310,91], EntityCow['Cow'/69, l='MpServer', x=178,94, y=71,00, z=324,94], EntityCow['Cow'/70, l='MpServer', x=181,78, y=71,00, z=325,22], EntityCow['Cow'/71, l='MpServer', x=167,78, y=71,00, z=304,72], EntityCow['Cow'/72, l='MpServer', x=164,28, y=70,00, z=275,69], EntitySpider['Spider'/132680, l='MpServer', x=237,91, y=20,00, z=225,50], EntitySpider['Spider'/132681, l='MpServer', x=236,50, y=20,00, z=227,50], EntitySheep['Sheep'/83, l='MpServer', x=170,56, y=68,00, z=185,34], EntityPig['Pig'/84, l='MpServer', x=176,97, y=72,00, z=336,34], EntityPig['Pig'/85, l='MpServer', x=189,91, y=70,00, z=343,16], EntityPig['Pig'/86, l='MpServer', x=191,81, y=70,00, z=334,19], EntityPig['Pig'/89, l='MpServer', x=197,06, y=69,00, z=318,06], EntityPig['Pig'/90, l='MpServer', x=195,25, y=70,00, z=254,31], EntityPig['Pig'/91, l='MpServer', x=186,38, y=70,00, z=307,19], EntityPig['Pig'/92, l='MpServer', x=194,09, y=70,00, z=320,25], EntityPig['Pig'/93, l='MpServer', x=194,50, y=70,00, z=332,50], EntityPig['Pig'/104, l='MpServer', x=237,09, y=70,00, z=213,06], EntityPig['Pig'/105, l='MpServer', x=154,63, y=67,00, z=232,94], EntityPig['Pig'/106, l='MpServer', x=202,25, y=70,00, z=213,38], EntityPig['Pig'/109, l='MpServer', x=174,94, y=68,00, z=229,97], EntityPig['Pig'/110, l='MpServer', x=179,06, y=70,00, z=307,22], EntityPig['Pig'/111, l='MpServer', x=152,97, y=72,00, z=316,19], EntityPig['Pig'/112, l='MpServer', x=171,91, y=70,00, z=283,91], EntitySheep['Sheep'/110967, l='MpServer', x=213,16, y=70,00, z=260,88], EntitySheep['Sheep'/110966, l='MpServer', x=189,97, y=69,00, z=223,03], EntitySheep['Sheep'/110969, l='MpServer', x=191,94, y=70,00, z=212,06], EntitySheep['Sheep'/110968, l='MpServer', x=198,94, y=70,00, z=255,06], EntitySheep['Sheep'/110971, l='MpServer', x=211,50, y=70,00, z=255,09], EntitySheep['Sheep'/110970, l='MpServer', x=184,81, y=69,00, z=244,69], EntitySheep['Sheep'/125, l='MpServer', x=264,06, y=67,00, z=269,13], EntitySheep['Sheep'/126, l='MpServer', x=251,88, y=67,00, z=251,25], EntitySheep['Sheep'/127, l='MpServer', x=177,03, y=70,00, z=292,09], EntitySheep['Sheep'/128, l='MpServer', x=255,38, y=64,00, z=260,25], EntityItem['item.item.rottenFlesh'/127882, l='MpServer', x=232,38, y=64,13, z=300,56], EntityItem['item.item.rottenFlesh'/127885, l='MpServer', x=248,03, y=63,13, z=277,16], EntityPig['Pig'/143, l='MpServer', x=231,31, y=71,00, z=206,50], EntityPig['Pig'/144, l='MpServer', x=241,50, y=68,00, z=214,50], EntityPig['Pig'/145, l='MpServer', x=243,50, y=66,00, z=213,50], EntityCreeper['Creeper'/134035, l='MpServer', x=146,00, y=15,00, z=224,50], EntityZombie['Zombie'/136851, l='MpServer', x=240,50, y=31,00, z=231,50], EntityPig['Pig'/146, l='MpServer', x=236,91, y=67,00, z=195,31], EntityPig['Pig'/147, l='MpServer', x=255,50, y=66,00, z=233,50], EntityZombie['Zombie'/136849, l='MpServer', x=236,50, y=31,00, z=231,50], EntityPig['Pig'/159, l='MpServer', x=257,50, y=66,00, z=237,50], EntityPig['Pig'/160, l='MpServer', x=264,09, y=66,00, z=239,88], EntityPig['Pig'/161, l='MpServer', x=269,19, y=67,00, z=240,16], EntityCreeper['Creeper'/127928, l='MpServer', x=210,50, y=32,00, z=212,50], EntityPig['Pig'/186, l='MpServer', x=290,47, y=67,00, z=222,66], EntityPig['Pig'/187, l='MpServer', x=292,50, y=67,00, z=224,13], EntityPig['Pig'/188, l='MpServer', x=294,78, y=66,00, z=225,50], EntityPig['Pig'/189, l='MpServer', x=293,19, y=66,00, z=225,50], EntityPig['Pig'/190, l='MpServer', x=301,22, y=67,00, z=233,53], EntityItem['item.item.apple'/132808, l='MpServer', x=201,78, y=75,13, z=260,03], EntityBat['Bat'/131556, l='MpServer', x=292,13, y=12,82, z=206,52], EntityZombie['Zombie'/136959, l='MpServer', x=286,21, y=28,02, z=221,58]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 269720288 bytes (257 MB) / 966393856 bytes (921 MB) up to 966393856 bytes (921 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn3072M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.82.1216 Minecraft Forge 10.13.1.1216 5 mods loaded, 5 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.82.1216} [Forge Mod Loader] (forge-1.7.10-10.13.1.1216-new.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.1.1216} [Minecraft Forge] (forge-1.7.10-10.13.1.1216-new.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	cfm{3.3.5} [§6MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.3.5(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ashjacksimukraftreloaded{1.0.2a} [Sim-U-Kraft Reloaded] (simukraft-1.7.10-1.0.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Launched Version: 1.7.10-Forge10.13.1.1216-new
	LWJGL: 2.9.1
	OpenGL: GeForce 9800 GTX/9800 GTX+/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by ashjack** [comment]
It looks like your world is corrupted. The mod is erroring when looking for the save file for your current world. Try creating a new world.

**Comment by ashjack** [comment]
Outdated version, please update to the newest version
