### ISSUE TITLE
Sim-U-Kraft 1.0.3 Crashes when building

### ISSUE THREAD

**Issue by Florals** [ashjack/Sim-U-Kraft-Reloaded#38]
Hello, I am running Sim-U-Craft 1.0.3 for 1.7.10.
I am having an issue with my Minecraft crashing whenever I begin to build a house. 
Before I am told to do the following, I've already tried these things: Re-installing Java, 
and Re-installing Minecraft.

Crash: 

Time: 3/31/15 1:16 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.google.common.collect.HashBiMap.delete(HashBiMap.java:143)
	at com.google.common.collect.HashBiMap.access$200(HashBiMap.java:52)
	at com.google.common.collect.HashBiMap$Itr.remove(HashBiMap.java:376)
	at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:231)
	at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:179)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2001)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.collect.HashBiMap.delete(HashBiMap.java:143)
	at com.google.common.collect.HashBiMap.access$200(HashBiMap.java:52)
	at com.google.common.collect.HashBiMap$Itr.remove(HashBiMap.java:376)
	at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:231)
	at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:179)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Floral'/2110, l='MpServer', x=1752.66, y=105.11, z=-812.60]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (109,64,100), Chunk: (at 13,4,4 in 6,6; contains blocks 96,0,96 to 111,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 301498 game time, 749389 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 94 total; [MoCEntityDeer['Deer'/2192, l='MpServer', x=1809.91, y=72.00, z=-757.88], MoCEntityDeer['Deer'/2193, l='MpServer', x=1808.53, y=72.00, z=-763.50], MoCEntityBunny['Bunny'/2194, l='MpServer', x=1810.78, y=72.00, z=-869.69], MoCEntityDeer['Deer'/2185, l='MpServer', x=1782.53, y=70.00, z=-866.53], MoCEntityHorse['WildHorse'/2184, l='MpServer', x=1712.72, y=68.00, z=-877.66], MoCEntityBunny['Bunny'/2187, l='MpServer', x=1700.41, y=65.00, z=-866.59], MoCEntityMouse['Mouse'/2186, l='MpServer', x=1780.53, y=79.00, z=-870.59], MoCEntityRaccoon['Raccoon'/2189, l='MpServer', x=1812.38, y=72.00, z=-862.63], MoCEntityHorse['WildHorse'/2188, l='MpServer', x=1804.72, y=68.18, z=-878.25], EntityZombie['Zombie'/2191, l='MpServer', x=1816.59, y=41.00, z=-758.00], EntityCreeper['Creeper'/2190, l='MpServer', x=1822.50, y=30.00, z=-762.50], EntityVillageGuard['Guard'/2177, l='MpServer', x=1683.94, y=64.00, z=-799.63], EntityFolk['entity.Folk.name'/11673, l='MpServer', x=1743.50, y=71.00, z=-814.50], EntitySheep['Sheep'/2176, l='MpServer', x=1695.19, y=68.00, z=-797.59], MoCEntityGoat['Goat'/2179, l='MpServer', x=1760.06, y=67.00, z=-744.06], MoCEntityHorse['WildHorse'/2178, l='MpServer', x=1735.34, y=80.00, z=-878.19], EntityFolk['entity.Folk.name'/11676, l='MpServer', x=1751.72, y=69.00, z=-799.50], EntityButterfly['entity.Butterfly.name'/23654, l='MpServer', x=1746.03, y=82.00, z=-857.75], MoCEntityDeer['Deer'/2180, l='MpServer', x=1697.16, y=63.00, z=-850.22], EntityFolk['entity.Folk.name'/2721, l='MpServer', x=1749.00, y=70.00, z=-813.00], EntityFolk['entity.Folk.name'/2715, l='MpServer', x=1758.38, y=70.00, z=-796.50], EntityFolk['entity.Folk.name'/2707, l='MpServer', x=1750.00, y=75.00, z=-811.00], EntityConBox['entity.ConBox.name'/2753, l='MpServer', x=1745.00, y=70.88, z=-815.00], EntityIronGolem['Iron Golem'/2032, l='MpServer', x=1706.28, y=65.00, z=-738.41], EntityItem['item.tile.SUKfarming'/2064, l='MpServer', x=1717.34, y=67.13, z=-749.06], EntityIronGolem['Iron Golem'/2033, l='MpServer', x=1705.50, y=64.00, z=-750.16], EntityIronGolem['Iron Golem'/2042, l='MpServer', x=1702.50, y=64.00, z=-750.97], EntityHuman['entity.MCA.EntityHuman.name'/2043, l='MpServer', x=1708.31, y=66.00, z=-764.69], EntityHuman['entity.MCA.EntityHuman.name'/2047, l='MpServer', x=1717.50, y=68.39, z=-763.69], EntityHuman['entity.MCA.EntityHuman.name'/2048, l='MpServer', x=1709.19, y=66.00, z=-764.62], EntityIronGolem['Iron Golem'/2023, l='MpServer', x=1700.72, y=63.00, z=-748.50], EntityIronGolem['Iron Golem'/2029, l='MpServer', x=1697.25, y=63.00, z=-752.38], EntityFolk['entity.Folk.name'/22685, l='MpServer', x=1757.38, y=70.00, z=-796.53], EntitySheep['Sheep'/2099, l='MpServer', x=1691.94, y=63.00, z=-762.53], MoCEntityDeer['Deer'/2098, l='MpServer', x=1688.53, y=63.00, z=-763.84], MoCEntityBigCat['BigCat'/2096, l='MpServer', x=1683.94, y=66.00, z=-752.91], MoCEntityDeer['Deer'/2100, l='MpServer', x=1692.50, y=65.00, z=-766.78], EntitySheep['Sheep'/2107, l='MpServer', x=1710.78, y=68.00, z=-793.50], MoCEntityHorse['WildHorse'/2106, l='MpServer', x=1704.00, y=64.00, z=-796.38], EntityIronGolem['Iron Golem'/2012, l='MpServer', x=1701.97, y=63.00, z=-741.16], MoCEntityDeer['Deer'/2083, l='MpServer', x=1755.53, y=69.00, z=-744.75], EntityIronGolem['Iron Golem'/2086, l='MpServer', x=1706.19, y=66.00, z=-756.25], EntityIronGolem['Iron Golem'/2084, l='MpServer', x=1699.28, y=63.00, z=-756.16], EntityZombie['Zombie'/2085, l='MpServer', x=1704.50, y=67.00, z=-766.31], EntityChicken['Chicken'/2091, l='MpServer', x=1693.81, y=63.00, z=-742.84], EntityChicken['Chicken'/2095, l='MpServer', x=1692.91, y=64.00, z=-736.72], EntityItem['item.tile.torch'/2133, l='MpServer', x=1742.88, y=75.13, z=-821.72], EntityItem['item.tile.torch'/2135, l='MpServer', x=1739.78, y=75.13, z=-823.88], EntityItem['item.tile.torch'/2134, l='MpServer', x=1741.31, y=75.13, z=-823.66], EntityItemFrame['entity.ItemFrame.name'/2141, l='MpServer', x=1739.50, y=75.50, z=-770.94], EntityItemFrame['entity.ItemFrame.name'/2140, l='MpServer', x=1738.50, y=75.50, z=-770.94], MoCEntityBigCat['BigCat'/2143, l='MpServer', x=1732.91, y=70.00, z=-774.53], EntityItemFrame['entity.ItemFrame.name'/2142, l='MpServer', x=1740.50, y=75.50, z=-770.94], MoCEntityBunny['Bunny'/2137, l='MpServer', x=1787.22, y=70.00, z=-810.78], EntityItem['item.tile.torch'/2136, l='MpServer', x=1738.25, y=75.13, z=-821.13], EntityItemFrame['entity.ItemFrame.name'/2139, l='MpServer', x=1737.50, y=75.50, z=-770.94], MoCEntityBunny['Bunny'/2119, l='MpServer', x=1711.31, y=67.00, z=-811.31], EntityButterfly['entity.Butterfly.name'/13553, l='MpServer', x=1738.75, y=75.72, z=-835.31], EntityClientPlayerMP['Floral'/2110, l='MpServer', x=1752.66, y=105.11, z=-812.60], EntityButterfly['entity.Butterfly.name'/22755, l='MpServer', x=1743.88, y=79.47, z=-875.75], MoCEntityDeer['Deer'/2125, l='MpServer', x=1741.28, y=68.00, z=-794.22], EntityItem['item.tile.ladder'/2120, l='MpServer', x=1739.50, y=71.13, z=-809.13], EntityItem['item.tile.torch'/2121, l='MpServer', x=1739.44, y=71.13, z=-809.13], MoCEntityBird['Bird'/2123, l='MpServer', x=1753.72, y=76.00, z=-831.09], EntitySheep['Sheep'/2167, l='MpServer', x=1792.53, y=72.00, z=-793.38], EntitySheep['Sheep'/2166, l='MpServer', x=1803.94, y=75.00, z=-788.97], MoCEntityGoat['Goat'/2165, l='MpServer', x=1797.81, y=74.00, z=-791.47], MoCEntityBird['Bird'/2164, l='MpServer', x=1803.84, y=84.00, z=-822.03], MoCEntityHorse['WildHorse'/2163, l='MpServer', x=1774.63, y=68.00, z=-851.50], MoCEntityBird['Bird'/2162, l='MpServer', x=1731.59, y=78.00, z=-862.44], EntityButterfly['entity.Butterfly.name'/22751, l='MpServer', x=1708.56, y=71.63, z=-826.25], EntityButterfly['entity.Butterfly.name'/2160, l='MpServer', x=1740.61, y=74.17, z=-758.25], MoCEntityHorse['WildHorse'/2175, l='MpServer', x=1753.75, y=78.00, z=-871.34], MoCEntityHorse['WildHorse'/2174, l='MpServer', x=1687.72, y=70.00, z=-803.41], MoCEntityBunny['Bunny'/2172, l='MpServer', x=1777.00, y=68.00, z=-850.06], MoCEntityBird['Bird'/2171, l='MpServer', x=1716.78, y=68.00, z=-856.75], MoCEntityBird['Bird'/2170, l='MpServer', x=1712.56, y=68.00, z=-856.94], MoCEntityBunny['Bunny'/2169, l='MpServer', x=1697.38, y=63.00, z=-844.44], EntityHuman['entity.MCA.EntityHuman.name'/2168, l='MpServer', x=1713.26, y=67.00, z=-775.47], MoCEntityBigCat['BigCat'/2150, l='MpServer', x=1711.44, y=70.00, z=-835.25], MoCEntityBigCat['BigCat'/2151, l='MpServer', x=1712.84, y=71.00, z=-832.88], MoCEntityBunny['Bunny'/2148, l='MpServer', x=1785.00, y=70.00, z=-822.97], MoCEntityMouse['Mouse'/2149, l='MpServer', x=1788.47, y=69.00, z=-832.25], MoCEntityHorse['WildHorse'/2146, l='MpServer', x=1762.94, y=68.00, z=-847.59], MoCEntityBird['Bird'/2147, l='MpServer', x=1774.41, y=68.00, z=-843.44], MoCEntityDeer['Deer'/2144, l='MpServer', x=1762.38, y=69.00, z=-836.47], MoCEntityBird['Bird'/2145, l='MpServer', x=1773.59, y=68.00, z=-840.78], EntityButterfly['entity.Butterfly.name'/2158, l='MpServer', x=1740.75, y=72.58, z=-761.50], EntityButterfly['entity.Butterfly.name'/2159, l='MpServer', x=1740.25, y=73.38, z=-758.25], MoCEntityHorse['WildHorse'/2156, l='MpServer', x=1755.66, y=77.00, z=-865.19], EntityButterfly['entity.Butterfly.name'/2157, l='MpServer', x=1741.22, y=73.69, z=-758.25], EntitySheep['Sheep'/2154, l='MpServer', x=1784.03, y=73.00, z=-781.91], EntitySheep['Sheep'/2155, l='MpServer', x=1708.34, y=64.00, z=-801.81], MoCEntityBunny['Bunny'/2153, l='MpServer', x=1785.34, y=69.00, z=-838.72]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.2
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 263219640 bytes (251 MB) / 644694016 bytes (614 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 9, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 14 mods loaded, 14 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	jammyfurniture{4.6} [Jammy Furniture Mod] (1.7.10_Jammy_Furniture_Mod_V4.6_RC1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	butterflymania{1.2.1} [Butterfly Mania] (butterflymania-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RadixCore{2.0.0} [RadixCore] (RadixCore-1.7.10-2.0.0-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MCA{5.0.0-beta} [Minecraft Comes Alive] (MCA-1.7.10-5.0.0-beta-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cfm{3.4.7} [ß9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	weeeflowers{1.7.2b} [Pam's Weee! Flowers] (Pams-Weee-Flowers-Mod-1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ashjacksimukraftreloaded{1.0.2a} [Sim-U-Kraft Reloaded] (simukraft-1.7.10-1.0.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	witchery{0.23.2} [Witchery] (witchery-1.7.10-0.23.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-10.2.46, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [NostalgiaCraft_10.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by ashjack** [comment]
Duplicate issue. See here: https://github.com/ashjack/Sim-U-Kraft-Reloaded/issues/14
