### ISSUE TITLE
Weird game glitches & sims not spawning

### ISSUE THREAD

**Issue by Minecraft9** [ashjack/Sim-U-Kraft-Reloaded#39]
Some of the glitches  are: if I mine block I cant collect it. sims not spawning. Any command i type in will not work. Everything else is frozen and not moving on my world except for me. I don't take damage in survival. These glitches SUCK plz help me!!!

**Comment by Minecraft9** [comment]
Also if I try to go to the title screen it will go to the game output

**Comment by ashjack** [comment]
Duplicate Issue. See https://github.com/ashjack/Sim-U-Kraft-Reloaded/issues/34
