### ISSUE TITLE
clinic catastrophe, cheesmakers bane

### ISSUE THREAD

**Issue by Gareld-Michael** [ashjack/Sim-U-Kraft-Reloaded#43]
The first thing that I had noticed while playing the game is that when building the clinic it is incomplete and glitches. I remember when building it that at some point the builder tried several times to place a block of some type and failed every time, then it looks like it skipped to the very end of the build without going any further up. The second thing that I noticed is that when the cheese maker tries to gather milk to make cheese, he gets the milk, drops it all, and for some reason is auto fired from his job.
Also their is a hole near the entrance of the clinic that bugs me but it is not a glitch.

**Comment by ashjack** [comment]
Clinic has been fixed in 1.0.4. There is already an issue for the cheesemaker, so I'm closing this one.
