### ISSUE TITLE
sim u kraft clinic and buger shop

### ISSUE THREAD

**Issue by ToxicAngel1** [ashjack/Sim-U-Kraft-Reloaded#44]
there not completing the building only half done and marker beams not showing
![2015-04-26_11 21 04](https://cloud.githubusercontent.com/assets/12125060/7338142/2188a06c-ec08-11e4-9e23-2faed5c0e18f.png)

**Comment by LNXlady** [comment]
Neither work for me either, in ver. 1.0.3b. The Clinic still functions (has no roof) but the Sim-U-burger doesn't build enough to keep the building.

**Comment by ashjack** [comment]
Fixed in 1.0.4.
