### ISSUE TITLE
A Common Crash Error in both Old Sim-u-kraft and Reloaded Version

### ISSUE THREAD

**Issue by Etheralslayer** [ashjack/Sim-U-Kraft-Reloaded#48]
Here is the log 

---- Minecraft Crash Report ----
// My bad.
Time: 5/11/15 8:02 PM
Description: Unexpected error
java.util.ConcurrentModificationException
at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:212)
at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:179)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2013)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Stacktrace:
at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:212)
at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:179)
-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityClientPlayerMP['EtheralSlayer'/484, l='MpServer', x=-33.51, y=64.62, z=320.85]]
Chunk stats: MultiplayerChunkCache: 36, 36
Level seed: 0
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options: 
Level spawn location: World: (20,64,256), Chunk: (at 4,4,0 in 1,16; contains blocks 16,0,256 to 31,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 24417 game time, 11160 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Forced entities: 66 total; [EntityItem['item.tile.sapling.oak'/1028, l='MpServer', x=-3.28, y=75.13, z=300.41], EntityItem['item.tile.sapling.oak'/3334, l='MpServer', x=-2.41, y=76.13, z=299.06], EntityFolk['entity.Folk.name'/1035, l='MpServer', x=12.06, y=69.00, z=325.34], EntityFolk['entity.Folk.name'/1040, l='MpServer', x=-6.50, y=69.00, z=305.31], EntityPig['Pig'/145, l='MpServer', x=-39.75, y=63.00, z=282.44], EntityChicken['Chicken'/146, l='MpServer', x=-30.46, y=66.25, z=297.22], EntityPig['Pig'/147, l='MpServer', x=-36.26, y=65.80, z=286.85], EntityItem['item.tile.sapling.oak'/1044, l='MpServer', x=-4.13, y=71.13, z=297.38], EntityPig['Pig'/149, l='MpServer', x=-39.13, y=66.00, z=361.34], EntityPig['Pig'/150, l='MpServer', x=-33.03, y=67.00, z=364.06], EntityBat['Bat'/2468, l='MpServer', x=-54.05, y=12.24, z=316.09], EntityPig['Pig'/164, l='MpServer', x=-22.94, y=70.00, z=282.41], EntityPig['Pig'/165, l='MpServer', x=-40.75, y=63.00, z=276.72], EntitySheep['Sheep'/166, l='MpServer', x=-23.84, y=72.81, z=271.66], EntitySheep['Sheep'/167, l='MpServer', x=-17.38, y=72.00, z=278.53], EntitySheep['Sheep'/168, l='MpServer', x=-21.50, y=69.00, z=278.19], EntitySheep['Sheep'/169, l='MpServer', x=-19.69, y=69.00, z=278.31], EntityChicken['Chicken'/171, l='MpServer', x=-20.59, y=71.00, z=292.59], EntityPig['Pig'/172, l='MpServer', x=-23.13, y=71.00, z=285.63], EntityPig['Pig'/173, l='MpServer', x=-31.98, y=69.81, z=300.40], EntityPig['Pig'/175, l='MpServer', x=-15.88, y=74.00, z=279.66], EntityPig['Pig'/176, l='MpServer', x=-15.50, y=72.00, z=281.47], EntityPig['Pig'/177, l='MpServer', x=-23.97, y=70.00, z=294.94], EntityPig['Pig'/179, l='MpServer', x=-28.93, y=66.00, z=325.42], EntityPig['Pig'/184, l='MpServer', x=-22.09, y=66.00, z=355.03], EntityPig['Pig'/185, l='MpServer', x=-4.22, y=65.00, z=366.84], EntityItem['item.tile.button'/2748, l='MpServer', x=-23.16, y=69.13, z=312.25], EntityItem['item.item.doorWood'/2750, l='MpServer', x=-24.22, y=69.13, z=324.03], EntityItem['item.tile.button'/2752, l='MpServer', x=-23.50, y=69.13, z=311.22], EntityChicken['Chicken'/193, l='MpServer', x=1.59, y=72.00, z=277.53], EntityItem['item.tile.button'/2754, l='MpServer', x=-24.78, y=69.13, z=311.16], EntityZombie['Zombie'/1987, l='MpServer', x=-36.50, y=20.00, z=335.50], EntityItem['item.item.doorWood'/2755, l='MpServer', x=-24.69, y=69.13, z=323.31], EntityZombie['Zombie'/1988, l='MpServer', x=-37.50, y=21.00, z=333.00], EntityItem['item.item.apple'/197, l='MpServer', x=0.28, y=70.13, z=302.13], EntitySkeleton['Skeleton'/2757, l='MpServer', x=-65.44, y=14.00, z=361.94], EntityChicken['Chicken'/198, l='MpServer', x=8.47, y=70.00, z=301.47], EntityPig['Pig'/200, l='MpServer', x=-0.88, y=69.00, z=317.97], EntityPig['Pig'/202, l='MpServer', x=1.53, y=67.00, z=322.28], EntitySkeleton['Skeleton'/1368, l='MpServer', x=-18.50, y=23.00, z=315.50], EntityFolk['entity.Folk.name'/1626, l='MpServer', x=-0.13, y=70.00, z=304.69], EntityPig['Pig'/222, l='MpServer', x=23.84, y=64.81, z=359.03], EntityCreeper['Creeper'/3038, l='MpServer', x=9.59, y=20.00, z=335.00], EntityPig['Pig'/223, l='MpServer', x=18.91, y=64.81, z=364.66], EntityPig['Pig'/224, l='MpServer', x=30.81, y=63.81, z=355.63], EntityPig['Pig'/96, l='MpServer', x=-77.50, y=64.00, z=329.50], EntityItem['item.tile.sapling.oak'/1249, l='MpServer', x=-4.69, y=69.13, z=312.13], EntityItem['item.tile.sapling.birch'/2017, l='MpServer', x=5.84, y=71.13, z=300.75], EntityPig['Pig'/97, l='MpServer', x=-79.03, y=64.00, z=327.50], EntityClientPlayerMP['EtheralSlayer'/484, l='MpServer', x=-33.51, y=64.62, z=320.85], EntityPig['Pig'/238, l='MpServer', x=34.97, y=64.81, z=350.09], EntitySheep['Sheep'/111, l='MpServer', x=-61.63, y=63.00, z=337.47], EntitySheep['Sheep'/112, l='MpServer', x=-59.84, y=63.00, z=324.75], EntitySheep['Sheep'/113, l='MpServer', x=-54.38, y=63.00, z=321.25], EntitySheep['Sheep'/114, l='MpServer', x=-61.04, y=63.00, z=329.87], EntityPig['Pig'/115, l='MpServer', x=-61.62, y=63.14, z=341.75], EntityPig['Pig'/118, l='MpServer', x=-51.50, y=66.00, z=359.50], EntitySquid['Squid'/2295, l='MpServer', x=-44.06, y=61.00, z=304.17], EntityPig['Pig'/119, l='MpServer', x=-54.50, y=66.00, z=357.50], EntitySquid['Squid'/2296, l='MpServer', x=-51.47, y=61.55, z=299.19], EntitySquid['Squid'/2297, l='MpServer', x=-55.81, y=60.43, z=308.15], EntitySquid['Squid'/2298, l='MpServer', x=-40.10, y=62.11, z=327.64], EntityCreeper['Creeper'/3322, l='MpServer', x=-14.50, y=30.00, z=293.50], EntitySquid['Squid'/2299, l='MpServer', x=-52.12, y=61.00, z=314.66], EntitySquid['Squid'/2301, l='MpServer', x=-49.76, y=61.36, z=297.46], EntitySquid['Squid'/2303, l='MpServer', x=-41.49, y=61.66, z=304.06]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 206065056 bytes (196 MB) / 417292288 bytes (397 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
FML: MCP v9.05 FML v7.10.140.1401 Minecraft Forge 10.13.3.1401 4 mods loaded, 4 mods active
mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
FML{7.10.140.1401} [Forge Mod Loader] (forge-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Forge{10.13.3.1401} [Minecraft Forge] (forge-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ashjacksimukraftreloaded{1.0.3a} [Sim-U-Kraft Reloaded] (Simukraft-Reloaded-1.7.10-1.0.3a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.3347' Renderer: 'Intel(R) HD Graphics 3000'
Launched Version: 1.7.10-Forge10.13.3.1401-1710ls
LWJGL: 2.9.1
OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.3347, Intel
GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)

**Comment by ashjack** [comment]
Duplicate Issue. See Issue https://github.com/ashjack/Sim-U-Kraft-Reloaded/issues/14
