### ISSUE TITLE
Sim-U-Burger and Clinic glitch?!

### ISSUE THREAD

**Issue by IceyWoo** [ashjack/Sim-U-Kraft-Reloaded#57]
When I try to build the sim-u-burger or clinic, they don't finish? The clinic doesn't have a roof or half the walls, and the sim-u-burger is like this, http://imgur.com/P3O03je Please help, I uninstalled everything and it still doesn't work, all of my worlds are deleted now because of it.

**Comment by ashjack** [comment]
Fixed in 1.0.4
