### ISSUE TITLE
crash, folk generation

### ISSUE THREAD

**Issue by stalkingkitty** [ashjack/Sim-U-Kraft-Reloaded#59]
when starting a world, its ask run simukraft etc etc, like always. 
But when starting simkraft when generating the first person it crashes.
note: machine Mac Osx versie 10.7.5

crash report
-----------------------------------------
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 7-9-15 13:04
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at ashjack.simukraftreloaded.folk.FolkData.generateRace(FolkData.java:2533)
	at ashjack.simukraftreloaded.folk.FolkData.<init>(FolkData.java:238)
	at ashjack.simukraftreloaded.folk.FolkData.generateNewFolk(FolkData.java:2116)
	at ashjack.simukraftreloaded.client.Gui.other.GuiRunMod.func_146284_a(GuiRunMod.java:86)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ashjack.simukraftreloaded.folk.FolkData.generateRace(FolkData.java:2533)
	at ashjack.simukraftreloaded.folk.FolkData.<init>(FolkData.java:238)
	at ashjack.simukraftreloaded.folk.FolkData.generateNewFolk(FolkData.java:2116)
	at ashjack.simukraftreloaded.client.Gui.other.GuiRunMod.func_146284_a(GuiRunMod.java:86)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: ashjack.simukraftreloaded.client.Gui.other.GuiRunMod

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['stalkingkitty'/176, l='MpServer', x=76,50, y=71,62, z=293,50]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (78,64,285), Chunk: (at 14,4,13 in 4,17; contains blocks 64,0,272 to 79,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 80 game time, 80 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 122 total; [EntitySkeleton['Skeleton'/800, l='MpServer', x=11,50, y=44,00, z=225,50], EntityBat['Bat'/575, l='MpServer', x=139,00, y=39,33, z=295,62], EntityFallingBlock['Falling Block'/1405, l='MpServer', x=76,50, y=35,42, z=262,50], EntityFallingBlock['Falling Block'/1404, l='MpServer', x=76,50, y=35,42, z=261,50], EntityFallingBlock['Falling Block'/1407, l='MpServer', x=75,50, y=35,42, z=262,50], EntityFallingBlock['Falling Block'/1406, l='MpServer', x=75,50, y=34,42, z=261,50], EntityPig['Pig'/38, l='MpServer', x=14,55, y=70,00, z=228,63], EntityFallingBlock['Falling Block'/1400, l='MpServer', x=77,50, y=35,42, z=263,50], EntityPig['Pig'/39, l='MpServer', x=13,45, y=70,00, z=229,45], EntityFallingBlock['Falling Block'/1397, l='MpServer', x=80,50, y=35,42, z=261,50], EntityPig['Pig'/42, l='MpServer', x=9,50, y=63,00, z=363,50], EntityFallingBlock['Falling Block'/1396, l='MpServer', x=79,50, y=36,42, z=262,50], EntityPig['Pig'/43, l='MpServer', x=9,50, y=63,00, z=363,50], EntitySkeleton['Skeleton'/798, l='MpServer', x=10,50, y=44,00, z=226,50], EntityFallingBlock['Falling Block'/1399, l='MpServer', x=77,50, y=35,42, z=262,50], EntityPig['Pig'/40, l='MpServer', x=14,69, y=70,00, z=230,71], EntityFallingBlock['Falling Block'/1398, l='MpServer', x=77,50, y=35,42, z=261,50], EntityPig['Pig'/41, l='MpServer', x=14,50, y=69,00, z=227,50], EntityFallingBlock['Falling Block'/1393, l='MpServer', x=78,50, y=35,42, z=263,50], EntityFallingBlock['Falling Block'/1392, l='MpServer', x=78,50, y=35,42, z=262,50], EntityZombie['Zombie'/794, l='MpServer', x=127,50, y=57,00, z=324,50], EntityFallingBlock['Falling Block'/1395, l='MpServer', x=79,50, y=35,42, z=261,50], EntityPig['Pig'/44, l='MpServer', x=9,50, y=63,00, z=363,50], EntityFallingBlock['Falling Block'/1394, l='MpServer', x=78,50, y=35,42, z=261,50], EntityPig['Pig'/45, l='MpServer', x=12,50, y=63,00, z=364,50], EntitySkeleton['Skeleton'/288, l='MpServer', x=127,50, y=31,00, z=346,50], EntitySkeleton['Skeleton'/289, l='MpServer', x=128,50, y=31,00, z=346,50], EntityFallingBlock['Falling Block'/1389, l='MpServer', x=80,50, y=35,42, z=263,50], EntityFallingBlock['Falling Block'/1390, l='MpServer', x=81,50, y=35,42, z=262,50], EntityFallingBlock['Falling Block'/1391, l='MpServer', x=79,50, y=35,42, z=263,50], EntityPig['Pig'/55, l='MpServer', x=28,50, y=75,00, z=309,50], EntityPig['Pig'/54, l='MpServer', x=32,50, y=76,00, z=308,50], EntityFallingBlock['Falling Block'/1385, l='MpServer', x=87,50, y=19,42, z=257,50], EntityFallingBlock['Falling Block'/1386, l='MpServer', x=81,50, y=35,42, z=263,50], EntityFallingBlock['Falling Block'/1387, l='MpServer', x=81,50, y=35,42, z=264,50], EntityPig['Pig'/57, l='MpServer', x=28,50, y=76,00, z=308,50], EntityPig['Pig'/56, l='MpServer', x=30,50, y=77,00, z=305,50], EntityPig['Pig'/63, l='MpServer', x=56,50, y=63,00, z=361,50], EntityPig['Pig'/62, l='MpServer', x=58,50, y=63,00, z=362,50], EntityPig['Pig'/61, l='MpServer', x=67,50, y=64,00, z=229,50], EntityBat['Bat'/539, l='MpServer', x=122,75, y=18,00, z=319,75], EntityPig['Pig'/60, l='MpServer', x=66,50, y=64,00, z=227,50], EntityItem['item.tile.log.oak'/69, l='MpServer', x=70,44, y=68,13, z=286,22], EntityPig['Pig'/64, l='MpServer', x=57,50, y=63,00, z=364,50], EntityPig['Pig'/65, l='MpServer', x=58,50, y=63,00, z=366,50], EntityItem['item.item.pickaxeWood'/76, l='MpServer', x=75,88, y=69,13, z=285,53], EntityCow['Cow'/77, l='MpServer', x=82,50, y=65,00, z=295,50], EntityZombie['Zombie'/1025, l='MpServer', x=108,50, y=39,00, z=234,50], EntityCow['Cow'/78, l='MpServer', x=85,50, y=85,00, z=292,53], EntityCreeper['Creeper'/1026, l='MpServer', x=113,50, y=39,00, z=235,50], EntityCow['Cow'/79, l='MpServer', x=82,50, y=66,00, z=290,50], EntityCreeper['Creeper'/893, l='MpServer', x=84,50, y=32,00, z=263,50], EntityZombie['Zombie'/1028, l='MpServer', x=12,50, y=34,00, z=235,50], EntityCreeper['Creeper'/623, l='MpServer', x=89,50, y=32,00, z=271,50], EntityItem['item.item.pickaxeWood'/73, l='MpServer', x=73,75, y=69,13, z=284,78], EntityZombie['Zombie'/892, l='MpServer', x=86,50, y=32,00, z=265,50], EntityZombie['Zombie'/1029, l='MpServer', x=12,50, y=34,00, z=237,50], EntityItem['item.item.pickaxeWood'/74, l='MpServer', x=73,13, y=69,13, z=285,63], EntitySkeleton['Skeleton'/895, l='MpServer', x=65,50, y=53,00, z=316,50], EntityItem['item.tile.wood.oak'/75, l='MpServer', x=73,81, y=69,13, z=284,44], EntityPig['Pig'/85, l='MpServer', x=102,50, y=63,00, z=244,50], EntityZombie['Zombie'/627, l='MpServer', x=119,50, y=57,00, z=366,50], EntityPig['Pig'/84, l='MpServer', x=103,58, y=64,25, z=241,40], EntityCreeper['Creeper'/626, l='MpServer', x=83,50, y=32,00, z=265,50], EntityPig['Pig'/87, l='MpServer', x=99,50, y=63,00, z=245,50], EntityCreeper['Creeper'/625, l='MpServer', x=85,50, y=32,00, z=263,50], EntityCreeper['Creeper'/624, l='MpServer', x=85,50, y=32,00, z=267,50], EntityPig['Pig'/86, l='MpServer', x=102,50, y=63,00, z=242,50], EntityCow['Cow'/80, l='MpServer', x=85,50, y=85,00, z=291,47], EntityBat['Bat'/330, l='MpServer', x=109,67, y=24,10, z=283,89], EntityPig['Pig'/88, l='MpServer', x=93,18, y=63,41, z=250,12], EntitySkeleton['Skeleton'/373, l='MpServer', x=106,50, y=39,00, z=277,50], EntitySkeleton['Skeleton'/371, l='MpServer', x=109,56, y=39,47, z=278,71], EntityItem['item.item.seeds'/852, l='MpServer', x=89,84, y=63,13, z=279,63], EntitySkeleton['Skeleton'/858, l='MpServer', x=137,50, y=13,00, z=324,50], EntityZombie['Zombie'/1330, l='MpServer', x=110,50, y=35,00, z=319,50], EntityZombie['Zombie'/1332, l='MpServer', x=110,50, y=35,00, z=318,50], EntityCreeper['Creeper'/834, l='MpServer', x=142,50, y=13,00, z=323,50], EntityCreeper['Creeper'/833, l='MpServer', x=141,50, y=13,00, z=324,50], EntityEnderman['Enderman'/838, l='MpServer', x=114,50, y=20,00, z=283,50], EntityZombie['Zombie'/836, l='MpServer', x=132,50, y=13,00, z=326,50], EntityZombie['Zombie'/837, l='MpServer', x=128,19, y=13,80, z=324,42], EntityPig['Pig'/126, l='MpServer', x=143,50, y=66,00, z=238,50], EntityZombie['Zombie'/1073, l='MpServer', x=114,50, y=23,25, z=280,30], EntityBat['Bat'/602, l='MpServer', x=143,39, y=40,07, z=276,22], EntityItem['item.tile.sapling.oak'/1221, l='MpServer', x=13,16, y=96,13, z=285,81], EntityItem['item.tile.sapling.oak'/1220, l='MpServer', x=15,19, y=95,13, z=283,81], EntityZombie['Zombie'/1231, l='MpServer', x=96,50, y=50,00, z=316,50], EntityZombie['Zombie'/1230, l='MpServer', x=92,50, y=50,00, z=321,50], EntityZombie['Zombie'/1232, l='MpServer', x=95,50, y=50,00, z=315,50], EntityItem['item.tile.sapling.oak'/690, l='MpServer', x=52,13, y=71,13, z=252,34], EntityCreeper['Creeper'/925, l='MpServer', x=124,50, y=54,00, z=353,50], EntityZombie['Zombie'/1259, l='MpServer', x=94,50, y=50,00, z=322,50], EntityZombie['Zombie'/1258, l='MpServer', x=97,50, y=50,00, z=318,50], EntityZombie['Zombie'/1257, l='MpServer', x=95,50, y=50,00, z=320,50], EntityClientPlayerMP['stalkingkitty'/176, l='MpServer', x=76,50, y=71,62, z=293,50], EntityZombie['Zombie'/1274, l='MpServer', x=26,50, y=40,00, z=235,50], EntityZombie['Zombie'/1275, l='MpServer', x=26,50, y=40,00, z=238,50], EntitySkeleton['Skeleton'/1273, l='MpServer', x=27,50, y=40,00, z=236,50], EntityItem['item.tile.sapling.oak'/1161, l='MpServer', x=38,75, y=78,13, z=254,12], EntityFallingBlock['Falling Block'/1411, l='MpServer', x=74,50, y=54,42, z=318,50], EntityFallingBlock['Falling Block'/1410, l='MpServer', x=74,50, y=53,42, z=317,50], EntityFallingBlock['Falling Block'/1409, l='MpServer', x=75,50, y=54,42, z=319,50], EntityFallingBlock['Falling Block'/1408, l='MpServer', x=75,50, y=54,42, z=318,50], EntityFallingBlock['Falling Block'/1415, l='MpServer', x=73,50, y=54,42, z=319,50], EntityFallingBlock['Falling Block'/1414, l='MpServer', x=73,50, y=54,42, z=317,50], EntityFallingBlock['Falling Block'/1413, l='MpServer', x=76,50, y=53,42, z=318,50], EntityFallingBlock['Falling Block'/1412, l='MpServer', x=74,50, y=54,42, z=319,50], EntityFallingBlock['Falling Block'/1419, l='MpServer', x=71,50, y=55,42, z=317,50], EntityZombie['Zombie'/212, l='MpServer', x=116,50, y=17,00, z=332,50], EntityFallingBlock['Falling Block'/1418, l='MpServer', x=71,50, y=55,42, z=316,50], EntityFallingBlock['Falling Block'/1417, l='MpServer', x=72,50, y=54,42, z=316,50], EntityFallingBlock['Falling Block'/1416, l='MpServer', x=73,50, y=55,42, z=318,50], EntityFallingBlock['Falling Block'/1422, l='MpServer', x=70,50, y=54,42, z=314,50], EntityFallingBlock['Falling Block'/1421, l='MpServer', x=72,50, y=55,42, z=318,50], EntityFallingBlock['Falling Block'/1420, l='MpServer', x=72,50, y=55,42, z=317,50], EntityZombie['Zombie'/211, l='MpServer', x=118,50, y=17,00, z=331,50], EntityBat['Bat'/494, l='MpServer', x=124,08, y=15,00, z=362,19], EntityCreeper['Creeper'/242, l='MpServer', x=109,50, y=39,00, z=279,67], EntityZombie['Zombie'/724, l='MpServer', x=123,84, y=17,89, z=307,81], EntityItem['item.tile.sapling.oak'/240, l='MpServer', x=18,88, y=88,13, z=298,88], EntityBat['Bat'/727, l='MpServer', x=87,71, y=20,39, z=243,26]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.7.5
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 145758984 bytes (139 MB) / 396570624 bytes (378 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 4 mods loaded, 4 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1277} [Forge Mod Loader] (forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1277} [Minecraft Forge] (forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ashjacksimukraftreloaded{1.0.4} [Sim-U-Kraft Reloaded] (Sim-U-Kraft Reloaded-1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1277
	LWJGL: 2.9.1
	OpenGL: Intel HD Graphics 3000 OpenGL Engine GL version 2.1 APPLE-7.32.12, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by MadMatty56** [comment]
Yeah, I'm getting the exact same issue when trying to generate any folk. This is my crash report:
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 13/09/15 14:13
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at ashjack.simukraftreloaded.folk.FolkData.generateRace(FolkData.java:2533)
	at ashjack.simukraftreloaded.folk.FolkData.<init>(FolkData.java:238)
	at ashjack.simukraftreloaded.folk.FolkData.generateNewFolk(FolkData.java:2116)
	at ashjack.simukraftreloaded.common.CommonTickHandler.onTickInGame(CommonTickHandler.java:152)
	at ashjack.simukraftreloaded.common.CommonTickHandler.tick(CommonTickHandler.java:43)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_8_CommonTickHandler_tick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 177879440 bytes (169 MB) / 456093696 bytes (434 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 4 mods loaded, 4 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ashjacksimukraftreloaded{1.0.4} [Sim-U-Kraft Reloaded] (Sim-U-Kraft Reloaded-1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['MadMatty57'/137, l='Sim-U-Kraft', x=-246.96, y=75.16, z=219.28]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by MadMatty56** [comment]
My computer:
Windows 10 Intel Core i5-3210M CPU @ 2.50GHz
64-bit Operating System
HP Pavillon Notebook

**Comment by ashjack** [comment]
This crash occurs because it cannot find the race folders. This means you have not installed the mod correctly. Please read the text file that came with the mod to learn the new installation.
