### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by aceliip** [ashjack/Sim-U-Kraft-Reloaded#60]
It keeps crashing with the stable 1.4 build for 1.7.10 MC whenever i choose a game mode.

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 10/8/15 4:59 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at ashjack.simukraftreloaded.folk.FolkData.generateRace(FolkData.java:2533)
	at ashjack.simukraftreloaded.folk.FolkData.<init>(FolkData.java:238)
	at ashjack.simukraftreloaded.folk.FolkData.generateNewFolk(FolkData.java:2116)
	at ashjack.simukraftreloaded.client.Gui.other.GuiRunMod.func_146284_a(GuiRunMod.java:86)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ashjack.simukraftreloaded.folk.FolkData.generateRace(FolkData.java:2533)
	at ashjack.simukraftreloaded.folk.FolkData.<init>(FolkData.java:238)
	at ashjack.simukraftreloaded.folk.FolkData.generateNewFolk(FolkData.java:2116)
	at ashjack.simukraftreloaded.client.Gui.other.GuiRunMod.func_146284_a(GuiRunMod.java:86)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: ashjack.simukraftreloaded.client.Gui.other.GuiRunMod

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Maxy501'/144, l='MpServer', x=150.50, y=79.62, z=240.50]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (156,64,248), Chunk: (at 12,4,8 in 9,15; contains blocks 144,0,240 to 159,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 101 game time, 101 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 51 total; [EntityZombie['Zombie'/1677, l='MpServer', x=78.50, y=31.00, z=240.50], EntityBat['Bat'/526, l='MpServer', x=100.48, y=16.47, z=234.02], EntityZombie['Zombie'/1678, l='MpServer', x=80.50, y=31.00, z=234.50], EntityZombie['Zombie'/1679, l='MpServer', x=79.50, y=31.00, z=241.50], EntityClientPlayerMP['Maxy501'/144, l='MpServer', x=150.50, y=79.62, z=240.50], EntityBat['Bat'/788, l='MpServer', x=218.30, y=47.00, z=226.94], EntityBat['Bat'/790, l='MpServer', x=224.47, y=48.38, z=234.57], EntityBat['Bat'/792, l='MpServer', x=209.49, y=45.69, z=218.03], EntityWolf['Wolf'/27, l='MpServer', x=126.50, y=68.00, z=262.50], EntityWolf['Wolf'/28, l='MpServer', x=129.60, y=69.00, z=259.41], EntityWolf['Wolf'/29, l='MpServer', x=123.50, y=69.00, z=258.66], EntityWolf['Wolf'/30, l='MpServer', x=128.38, y=69.00, z=258.25], EntitySkeleton['Skeleton'/1067, l='MpServer', x=175.50, y=17.00, z=270.50], EntitySkeleton['Skeleton'/1069, l='MpServer', x=199.50, y=25.00, z=180.50], EntityZombie['Zombie'/815, l='MpServer', x=223.50, y=23.00, z=221.50], EntitySkeleton['Skeleton'/1071, l='MpServer', x=200.50, y=25.00, z=180.50], EntityWitch['Witch'/1072, l='MpServer', x=186.50, y=25.00, z=175.50], EntitySquid['Squid'/185, l='MpServer', x=116.64, y=61.03, z=276.34], EntityWolf['Wolf'/60, l='MpServer', x=147.50, y=84.00, z=190.50], EntitySpider['Spider'/1084, l='MpServer', x=220.50, y=47.00, z=227.50], EntityWolf['Wolf'/61, l='MpServer', x=144.50, y=83.00, z=189.50], EntityWolf['Wolf'/62, l='MpServer', x=143.50, y=84.00, z=187.50], EntityWolf['Wolf'/63, l='MpServer', x=142.50, y=79.00, z=189.50], EntityChicken['Chicken'/64, l='MpServer', x=142.50, y=66.00, z=295.50], EntityChicken['Chicken'/65, l='MpServer', x=142.50, y=66.00, z=293.50], EntitySkeleton['Skeleton'/1729, l='MpServer', x=100.50, y=23.00, z=245.50], EntityChicken['Chicken'/66, l='MpServer', x=142.50, y=70.00, z=291.50], EntityChicken['Chicken'/67, l='MpServer', x=143.50, y=66.00, z=292.50], EntitySkeleton['Skeleton'/1091, l='MpServer', x=212.50, y=45.00, z=218.50], EntitySkeleton['Skeleton'/1092, l='MpServer', x=211.50, y=45.00, z=218.50], EntityWolf['Wolf'/72, l='MpServer', x=154.31, y=76.00, z=237.69], EntitySkeleton['Skeleton'/968, l='MpServer', x=75.26, y=50.00, z=257.43], EntityWolf['Wolf'/73, l='MpServer', x=161.52, y=77.67, z=233.44], EntitySkeleton['Skeleton'/969, l='MpServer', x=76.50, y=54.00, z=259.50], EntityWolf['Wolf'/74, l='MpServer', x=158.72, y=75.00, z=230.63], EntityZombie['Zombie'/970, l='MpServer', x=77.50, y=54.00, z=260.50], EntitySkeleton['Skeleton'/1610, l='MpServer', x=114.50, y=25.00, z=235.50], EntityWolf['Wolf'/75, l='MpServer', x=155.52, y=76.00, z=243.75], EntityBat['Bat'/599, l='MpServer', x=112.08, y=27.79, z=213.29], EntityWolf['Wolf'/87, l='MpServer', x=225.50, y=63.00, z=318.50], EntityBat['Bat'/216, l='MpServer', x=82.58, y=49.10, z=253.53], EntitySpider['Spider'/864, l='MpServer', x=85.03, y=57.00, z=260.94], EntitySpider['Spider'/869, l='MpServer', x=90.50, y=57.00, z=260.50], EntityBat['Bat'/487, l='MpServer', x=86.82, y=30.00, z=214.50], EntitySkeleton['Skeleton'/1767, l='MpServer', x=206.50, y=29.00, z=185.50], EntityBat['Bat'/488, l='MpServer', x=92.15, y=31.00, z=210.33], EntityCreeper['Creeper'/1768, l='MpServer', x=204.50, y=29.00, z=186.50], EntityZombie['Zombie'/1641, l='MpServer', x=80.50, y=48.00, z=255.50], EntityBat['Bat'/492, l='MpServer', x=95.53, y=31.18, z=210.42], EntityEnderman['Enderman'/1398, l='MpServer', x=71.50, y=47.00, z=255.50], EntityWitch['Witch'/1399, l='MpServer', x=73.74, y=45.00, z=251.76]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 597497656 bytes (569 MB) / 1265455104 bytes (1206 MB) up to 7408844800 bytes (7065 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAA	ResourceLoader{1.2} [Resource Loader] (ResourceLoader-1.2 (1).jar) 
	UCHIJAAAA	ashjacksimukraftreloaded{1.0.4} [Sim-U-Kraft Reloaded] (Sim-U-Kraft Reloaded-1.0.4.jar) 
	UCHIJAAAA	sus{4.1.1} [Superheroes Unlimited Mod] (Superheroes Unlimited Mod-1.7.10-4.1.1.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 6520G'
	Launched Version: 1.7.10-Forge10.13.4.1492-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6520G GL version 4.5.13399 Compatibility Profile Context 15.201.1151.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by ashjack** [comment]
You have not installed the mod correctly. There is a new installation method. Please read the enclosed readme in the mod zip file.
