### ISSUE TITLE
1.0.4 Sim error

### ISSUE THREAD

**Issue by Gareld-Michael** [ashjack/Sim-U-Kraft-Reloaded#63]
When I was playing 1.0.4 in a new world a Sim spawned in, like normal. About 20 minutes of play later (I was trying to find the sim-u-constructor recipe an did other normal stuff) I entered creative got some sim-u-stuff (not literally an object) (sim-u : constructor, miner, farmer + 4 markers) and tried to get my sim to build a house after I reentered survival. When I tried to hire her, other names from a another save that had been removed, because of a problem, appeared with hers and when I tried to hire her and another one of them later, neither one would come. Even after I chose a building they did not come there to build it. I'm thinking as I'm typing this that it may be a problem from another save in a different version that I didn't expect to carry over. I'll then reload Minercraft and try again. However if there is a way to prevent any form of carry over I would ask you to try your best to remove it. Thanks for listening.

**Comment by Gareld-Michael** [comment]
sorry if this is basically the same problem as before. So please be patient with me, I'm never really certain if it is the same. Thanks.

**Comment by xXXIMMATTHEWXXx** [comment]
Hello! I am porting this port to try and update the inactivity from the person who updated this mod. Please [recreate the issue here.](https://github.com/xXXIMMATTHEWXXx/Sim-u-kraft-Restored)

**Comment by ashjack** [comment]
This bug occurs when you load another save in the same session of Minecraft. To avoid this issue, once you save and quit a world, close Minecraft and reload it to play a different world.
