### ISSUE TITLE
Difficulty menu crash.

### ISSUE THREAD

**Issue by Halofreak1215** [ashjack/Sim-U-Kraft-Reloaded#65]
When I load/create a world, I select a difficulty, then it just crashes.

**Comment by ashjack** [comment]
Please provide a crash report, as I am unable to fix the problem without one. Thanks

**Comment by ashjack** [comment]
Crashes when choosing difficulty are down to the mod being incorrectly installed.

**Comment by Halofreak1215** [comment]
I probably did something wrong and didn't realize it, like an idiot.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 10/25/15 11:36 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at ashjack.simukraftreloaded.folk.FolkData.generateRace(FolkData.java:2533)
	at ashjack.simukraftreloaded.folk.FolkData.<init>(FolkData.java:238)
	at ashjack.simukraftreloaded.folk.FolkData.generateNewFolk(FolkData.java:2116)
	at ashjack.simukraftreloaded.client
https://github.com/ashjack/Sim-U-Kraft-Reloaded/issues/65#.Gui.other.GuiRunMod.func_146284_a(GuiRunMod.java:86)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ashjack.simukraftreloaded.folk.FolkData.generateRace(FolkData.java:2533)
	at ashjack.simukraftreloaded.folk.FolkData.<init>(FolkData.java:238)
	at ashjack.simukraftreloaded.folk.FolkData.generateNewFolk(FolkData.java:2116)
	at ashjack.simukraftreloaded.client.Gui.other.GuiRunMod.func_146284_a(GuiRunMod.java:86)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: ashjack.simukraftreloaded.client.Gui.other.GuiRunMod

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Halofreak1215'/288, l='MpServer', x=-234.50, y=65.62, z=-25.50]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-225,64,-28), Chunk: (at 15,4,4 in -15,-2; contains blocks -240,0,-32 to -225,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 102 game time, 102 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 166 total; [EntitySquid['Squid'/512, l='MpServer', x=-193.75, y=50.36, z=-39.56], EntitySquid['Squid'/513, l='MpServer', x=-190.61, y=48.77, z=-43.94], EntitySquid['Squid'/514, l='MpServer', x=-183.23, y=49.28, z=-44.14], EntitySquid['Squid'/515, l='MpServer', x=-191.78, y=49.75, z=-43.48], EntitySquid['Squid'/516, l='MpServer', x=-187.28, y=50.37, z=-43.84], EntitySquid['Squid'/558, l='MpServer', x=-242.09, y=60.36, z=25.94], EntitySquid['Squid'/559, l='MpServer', x=-246.30, y=58.30, z=25.15], EntitySquid['Squid'/560, l='MpServer', x=-244.14, y=59.27, z=23.99], EntitySquid['Squid'/561, l='MpServer', x=-248.77, y=59.80, z=22.78], EntitySquid['Squid'/562, l='MpServer', x=-247.12, y=58.36, z=35.15], EntitySquid['Squid'/563, l='MpServer', x=-249.46, y=58.86, z=30.93], EntitySquid['Squid'/564, l='MpServer', x=-251.31, y=60.36, z=33.03], EntitySquid['Squid'/565, l='MpServer', x=-250.35, y=60.41, z=34.03], EntitySquid['Squid'/566, l='MpServer', x=-247.31, y=59.36, z=28.48], EntitySquid['Squid'/567, l='MpServer', x=-246.95, y=60.36, z=23.66], EntitySquid['Squid'/569, l='MpServer', x=-244.94, y=60.16, z=22.83], EntitySheep['Sheep'/69, l='MpServer', x=-303.50, y=66.00, z=-16.50], EntitySquid['Squid'/582, l='MpServer', x=-201.69, y=56.96, z=-9.61], EntitySheep['Sheep'/70, l='MpServer', x=-301.50, y=94.00, z=-18.50], EntitySquid['Squid'/583, l='MpServer', x=-205.31, y=58.38, z=-10.70], EntitySheep['Sheep'/71, l='MpServer', x=-298.59, y=83.00, z=-22.50], EntitySquid['Squid'/584, l='MpServer', x=-200.03, y=57.87, z=-11.63], EntitySheep['Sheep'/72, l='MpServer', x=-302.50, y=78.00, z=-23.50], EntitySquid['Squid'/585, l='MpServer', x=-209.50, y=58.43, z=-9.52], EntitySheep['Sheep'/73, l='MpServer', x=-306.50, y=64.00, z=4.50], EntitySquid['Squid'/586, l='MpServer', x=-209.51, y=56.93, z=-2.34], EntitySheep['Sheep'/74, l='MpServer', x=-305.50, y=63.00, z=6.50], EntitySquid['Squid'/587, l='MpServer', x=-208.91, y=58.14, z=-8.28], EntitySheep['Sheep'/75, l='MpServer', x=-306.50, y=64.00, z=4.50], EntitySquid['Squid'/588, l='MpServer', x=-204.46, y=57.66, z=-7.97], EntitySheep['Sheep'/76, l='MpServer', x=-310.50, y=64.00, z=2.50], EntitySquid['Squid'/589, l='MpServer', x=-206.48, y=58.30, z=-9.55], EntityMinecartChest['entity.MinecartChest.name'/77, l='MpServer', x=-302.50, y=39.50, z=40.50], EntityChicken['Chicken'/78, l='MpServer', x=-283.29, y=74.00, z=-63.02], EntitySquid['Squid'/591, l='MpServer', x=-206.40, y=56.75, z=-7.48], EntityChicken['Chicken'/79, l='MpServer', x=-283.50, y=72.00, z=-64.50], EntitySquid['Squid'/592, l='MpServer', x=-206.47, y=58.45, z=-10.53], EntityChicken['Chicken'/80, l='MpServer', x=-286.66, y=72.00, z=-60.56], EntityChicken['Chicken'/81, l='MpServer', x=-285.50, y=72.00, z=-63.50], EntityMinecartChest['entity.MinecartChest.name'/82, l='MpServer', x=-291.50, y=44.50, z=49.50], EntitySheep['Sheep'/83, l='MpServer', x=-268.41, y=64.00, z=-32.53], EntitySheep['Sheep'/84, l='MpServer', x=-270.53, y=64.00, z=-30.53], EntitySheep['Sheep'/85, l='MpServer', x=-269.47, y=64.00, z=-29.47], EntitySheep['Sheep'/86, l='MpServer', x=-269.47, y=64.00, z=-29.47], EntitySheep['Sheep'/87, l='MpServer', x=-249.47, y=65.00, z=-36.47], EntitySheep['Sheep'/88, l='MpServer', x=-248.50, y=65.00, z=-34.50], EntitySquid['Squid'/600, l='MpServer', x=-170.51, y=56.24, z=-81.21], EntitySheep['Sheep'/89, l='MpServer', x=-250.53, y=65.00, z=-36.47], EntitySheep['Sheep'/90, l='MpServer', x=-250.53, y=64.00, z=-37.53], EntitySheep['Sheep'/91, l='MpServer', x=-216.47, y=64.00, z=-58.47], EntitySheep['Sheep'/92, l='MpServer', x=-216.47, y=64.00, z=-58.47], EntitySheep['Sheep'/93, l='MpServer', x=-216.50, y=64.00, z=-59.53], EntitySheep['Sheep'/94, l='MpServer', x=-217.53, y=65.00, z=-57.47], EntitySheep['Sheep'/95, l='MpServer', x=-220.50, y=64.00, z=-43.50], EntitySheep['Sheep'/96, l='MpServer', x=-223.50, y=64.00, z=-47.50], EntitySheep['Sheep'/97, l='MpServer', x=-225.50, y=72.00, z=-48.50], EntitySheep['Sheep'/98, l='MpServer', x=-226.50, y=64.00, z=-48.50], EntitySheep['Sheep'/99, l='MpServer', x=-220.49, y=64.00, z=-17.47], EntitySheep['Sheep'/100, l='MpServer', x=-220.47, y=64.00, z=-20.52], EntitySheep['Sheep'/101, l='MpServer', x=-219.47, y=64.00, z=-19.31], EntitySheep['Sheep'/102, l='MpServer', x=-220.66, y=64.00, z=-18.53], EntityChicken['Chicken'/103, l='MpServer', x=-223.70, y=64.00, z=-17.81], EntityChicken['Chicken'/104, l='MpServer', x=-221.38, y=64.00, z=-18.53], EntityChicken['Chicken'/105, l='MpServer', x=-224.33, y=65.00, z=-19.56], EntityChicken['Chicken'/106, l='MpServer', x=-218.50, y=64.00, z=-19.50], EntitySheep['Sheep'/107, l='MpServer', x=-221.53, y=64.00, z=-20.50], EntitySheep['Sheep'/108, l='MpServer', x=-219.50, y=65.00, z=-22.50], EntitySheep['Sheep'/109, l='MpServer', x=-217.50, y=64.00, z=-22.50], EntitySheep['Sheep'/110, l='MpServer', x=-217.50, y=64.00, z=-22.50], EntityChicken['Chicken'/111, l='MpServer', x=-223.50, y=63.00, z=-9.50], EntityChicken['Chicken'/112, l='MpServer', x=-219.50, y=63.00, z=-12.50], EntityChicken['Chicken'/113, l='MpServer', x=-217.50, y=63.00, z=-12.50], EntityChicken['Chicken'/114, l='MpServer', x=-219.50, y=74.00, z=-13.50], EntityItem['item.tile.mushroom'/115, l='MpServer', x=-193.28, y=29.13, z=-46.68], EntitySquid['Squid'/641, l='MpServer', x=-209.03, y=57.37, z=11.65], EntitySquid['Squid'/642, l='MpServer', x=-208.36, y=56.66, z=10.12], EntitySquid['Squid'/644, l='MpServer', x=-215.24, y=56.88, z=9.48], EntityBat['Bat'/1156, l='MpServer', x=-272.25, y=14.27, z=52.25], EntitySquid['Squid'/645, l='MpServer', x=-209.65, y=56.94, z=7.06], EntitySquid['Squid'/646, l='MpServer', x=-211.78, y=57.33, z=-3.22], EntitySquid['Squid'/647, l='MpServer', x=-214.13, y=57.00, z=6.70], EntitySquid['Squid'/648, l='MpServer', x=-221.28, y=56.18, z=10.41], EntitySquid['Squid'/649, l='MpServer', x=-224.94, y=56.20, z=8.79], EntitySquid['Squid'/654, l='MpServer', x=-169.32, y=46.36, z=-32.23], EntitySquid['Squid'/655, l='MpServer', x=-173.65, y=48.43, z=-27.63], EntitySquid['Squid'/657, l='MpServer', x=-171.48, y=48.44, z=-30.03], EntitySquid['Squid'/659, l='MpServer', x=-173.40, y=48.22, z=-31.13], EntitySquid['Squid'/660, l='MpServer', x=-174.88, y=48.00, z=-24.50], EntitySquid['Squid'/661, l='MpServer', x=-177.84, y=46.14, z=-25.42], EntityItem['item.item.seeds'/1205, l='MpServer', x=-215.66, y=62.13, z=-65.25], EntityFallingBlock['Falling Block'/1229, l='MpServer', x=-221.50, y=37.16, z=-19.50], EntityFallingBlock['Falling Block'/1230, l='MpServer', x=-222.50, y=37.16, z=-19.50], EntityFallingBlock['Falling Block'/1231, l='MpServer', x=-221.50, y=38.16, z=-18.50], EntityFallingBlock['Falling Block'/1232, l='MpServer', x=-222.50, y=37.16, z=-18.50], EntityFallingBlock['Falling Block'/1233, l='MpServer', x=-220.50, y=38.16, z=-18.50], EntityFallingBlock['Falling Block'/1234, l='MpServer', x=-222.50, y=38.16, z=-17.50], EntityFallingBlock['Falling Block'/1235, l='MpServer', x=-221.50, y=38.16, z=-17.50], EntityFallingBlock['Falling Block'/1236, l='MpServer', x=-222.50, y=38.16, z=-16.50], EntityFallingBlock['Falling Block'/1237, l='MpServer', x=-221.50, y=38.16, z=-16.50], EntityFallingBlock['Falling Block'/1238, l='MpServer', x=-223.50, y=37.16, z=-18.50], EntityFallingBlock['Falling Block'/1239, l='MpServer', x=-223.50, y=37.16, z=-17.50], EntityFallingBlock['Falling Block'/1240, l='MpServer', x=-223.50, y=37.16, z=-16.50], EntityFallingBlock['Falling Block'/1241, l='MpServer', x=-222.50, y=38.16, z=-15.50], EntityFallingBlock['Falling Block'/1242, l='MpServer', x=-221.50, y=38.16, z=-15.50], EntityFallingBlock['Falling Block'/1243, l='MpServer', x=-220.50, y=38.16, z=-17.50], EntityFallingBlock['Falling Block'/1244, l='MpServer', x=-220.50, y=38.16, z=-16.50], EntityFallingBlock['Falling Block'/1245, l='MpServer', x=-222.50, y=38.16, z=-14.50], EntityFallingBlock['Falling Block'/1246, l='MpServer', x=-223.50, y=37.16, z=-15.50], EntityFallingBlock['Falling Block'/1247, l='MpServer', x=-221.50, y=38.16, z=-14.50], EntityFallingBlock['Falling Block'/1248, l='MpServer', x=-220.50, y=38.16, z=-15.50], EntityFallingBlock['Falling Block'/1249, l='MpServer', x=-221.50, y=38.16, z=-13.50], EntitySquid['Squid'/746, l='MpServer', x=-224.53, y=50.34, z=24.16], EntitySquid['Squid'/747, l='MpServer', x=-229.37, y=50.43, z=25.03], EntitySquid['Squid'/748, l='MpServer', x=-233.06, y=50.34, z=24.19], EntitySquid['Squid'/749, l='MpServer', x=-228.03, y=49.88, z=28.82], EntitySquid['Squid'/750, l='MpServer', x=-226.96, y=49.14, z=28.11], EntitySquid['Squid'/751, l='MpServer', x=-218.63, y=49.66, z=27.50], EntitySquid['Squid'/752, l='MpServer', x=-222.50, y=50.44, z=31.66], EntitySquid['Squid'/753, l='MpServer', x=-225.47, y=49.01, z=23.38], EntitySquid['Squid'/754, l='MpServer', x=-218.75, y=48.87, z=23.26], EntitySquid['Squid'/755, l='MpServer', x=-217.50, y=49.83, z=18.52], EntitySquid['Squid'/756, l='MpServer', x=-215.22, y=50.39, z=22.76], EntitySquid['Squid'/757, l='MpServer', x=-216.27, y=50.35, z=19.36], EntityFallingBlock['Falling Block'/1303, l='MpServer', x=-201.50, y=23.73, z=7.50], EntityFallingBlock['Falling Block'/1307, l='MpServer', x=-203.50, y=23.73, z=8.50], EntityFallingBlock['Falling Block'/1308, l='MpServer', x=-200.50, y=58.96, z=-58.50], EntityFallingBlock['Falling Block'/1309, l='MpServer', x=-199.50, y=58.96, z=-57.50], EntityFallingBlock['Falling Block'/1323, l='MpServer', x=-201.50, y=59.96, z=-56.50], EntityFallingBlock['Falling Block'/1326, l='MpServer', x=-195.50, y=30.96, z=-8.50], EntityFallingBlock['Falling Block'/1327, l='MpServer', x=-195.50, y=30.96, z=-7.50], EntityFallingBlock['Falling Block'/1329, l='MpServer', x=-197.50, y=31.96, z=-9.50], EntityFallingBlock['Falling Block'/1334, l='MpServer', x=-198.50, y=31.96, z=-9.50], EntityFallingBlock['Falling Block'/1335, l='MpServer', x=-197.50, y=31.96, z=-10.50], EntityFallingBlock['Falling Block'/1336, l='MpServer', x=-198.50, y=31.96, z=-10.50], EntityFallingBlock['Falling Block'/1337, l='MpServer', x=-198.50, y=31.96, z=-8.50], EntityFallingBlock['Falling Block'/1339, l='MpServer', x=-199.50, y=31.96, z=-9.50], EntityClientPlayerMP['Halofreak1215'/288, l='MpServer', x=-234.50, y=65.62, z=-25.50], EntityFallingBlock['Falling Block'/1386, l='MpServer', x=-170.50, y=23.96, z=-21.50], EntityFallingBlock['Falling Block'/1387, l='MpServer', x=-169.50, y=23.96, z=-21.50], EntityFallingBlock['Falling Block'/1388, l='MpServer', x=-171.50, y=23.96, z=-21.50], EntityFallingBlock['Falling Block'/1389, l='MpServer', x=-172.50, y=23.96, z=-21.50], EntityFallingBlock['Falling Block'/1390, l='MpServer', x=-171.50, y=23.96, z=-20.50], EntityFallingBlock['Falling Block'/1391, l='MpServer', x=-170.50, y=23.96, z=-20.50], EntityFallingBlock['Falling Block'/1392, l='MpServer', x=-169.50, y=23.96, z=-20.50], EntityFallingBlock['Falling Block'/1393, l='MpServer', x=-168.50, y=23.96, z=-21.50], EntityBat['Bat'/893, l='MpServer', x=-203.25, y=12.00, z=-38.50], EntityBat['Bat'/905, l='MpServer', x=-167.96, y=18.14, z=14.35], EntityBat['Bat'/937, l='MpServer', x=-300.49, y=45.58, z=-89.53], EntityFallingBlock['Falling Block'/1456, l='MpServer', x=-167.50, y=29.15, z=-13.50], EntityFallingBlock['Falling Block'/1457, l='MpServer', x=-169.50, y=29.15, z=-13.50], EntitySquid['Squid'/434, l='MpServer', x=-169.85, y=48.71, z=-55.01], EntityFallingBlock['Falling Block'/1458, l='MpServer', x=-168.50, y=29.15, z=-13.50], EntitySquid['Squid'/435, l='MpServer', x=-177.20, y=50.37, z=-53.26], EntityFallingBlock['Falling Block'/1459, l='MpServer', x=-166.50, y=29.15, z=-13.50], EntitySquid['Squid'/436, l='MpServer', x=-174.94, y=50.00, z=-56.22], EntityFallingBlock['Falling Block'/1460, l='MpServer', x=-170.50, y=29.15, z=-13.50], EntitySquid['Squid'/441, l='MpServer', x=-173.22, y=49.36, z=-56.56], EntitySquid['Squid'/442, l='MpServer', x=-176.55, y=50.38, z=-55.78], EntitySquid['Squid'/444, l='MpServer', x=-175.28, y=50.31, z=-60.43], EntityBat['Bat'/995, l='MpServer', x=-200.41, y=16.42, z=2.94], EntitySquid['Squid'/505, l='MpServer', x=-185.35, y=49.81, z=-44.51], EntitySquid['Squid'/507, l='MpServer', x=-185.59, y=48.50, z=-43.75], EntitySquid['Squid'/508, l='MpServer', x=-188.71, y=50.38, z=-37.31], EntitySquid['Squid'/509, l='MpServer', x=-191.38, y=48.69, z=-41.17], EntitySquid['Squid'/510, l='MpServer', x=-190.87, y=48.36, z=-38.88], EntitySquid['Squid'/511, l='MpServer', x=-191.99, y=50.41, z=-40.07]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 138747752 bytes (132 MB) / 361238528 bytes (344 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1517 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1517} [Minecraft Forge] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJAAAA	ResourceLoader{1.2} [Resource Loader] (ResourceLoader-1.2.jar) 
	UCHIJAAAA	ashjacksimukraftreloaded{1.0.4} [Sim-U-Kraft Reloaded] (Sim-U-Kraft Reloaded-1.0.4.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.7.10-Forge10.13.4.1517-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Halofreak1215** [comment]
Yup, I'm stupid. I fixed it.
