### ISSUE TITLE
Builder won't place slabs correctly

### ISSUE THREAD

**Issue by StarTrickel** [ashjack/Sim-U-Kraft-Reloaded#71]
When the builder is building something that has slabs, he puts it like a regular block. This happens in all the buildings in normal mode. To destroy it you need a pickaxe, even if is breaking wood, and you get two slabs of the block.

**Comment by ashjack** [comment]
This is not a bug with the mod; it is because some of the buildings use the very early slabs. To get around this, simply update the building file, or don't build the building.
