### ISSUE TITLE
Interiour gets not build, (Beds etc. pop up) (1.7.10)

### ISSUE THREAD

**Issue by Elfblood** [ashjack/Sim-U-Kraft-Reloaded#75]
When a builder builds something they try to set furnaces, beds, signs etc. but this things keep popping and floating as items in the world.

mods:
Twilight Forest
BoP
Buildcraft
Forestry
Thermal Expansion
M-Ores
M-Swords
M-Arrows
Reptiles
MoCreatures

**Comment by xXXIMMATTHEWXXx** [comment]
Hello! I am porting this port to try and update the inactivity from the person who updated this mod. Please [recreate the issue here.](https://github.com/xXXIMMATTHEWXXx/Sim-u-kraft-Restored)

**Comment by ashjack** [comment]
Fixed in 1.0.4c - to be released
