### ISSUE TITLE
Skins Not Show Up?

### ISSUE THREAD

**Issue by SingMinecraft** [ashjack/Sim-U-Kraft-Reloaded#77]
So, I have Sim U Kraft version 1.7.10 and when I first opened it, I had everything needed to run it with Optifine and More Players Mod also in the mods folder. It was running perfectly but the skins on the NPC'S were purple and black. Is there anything I can do to make them show up or do I have to deal with it?
![2016-03-31_20 33 26](https://cloud.githubusercontent.com/assets/18202605/14196495/43e1e656-f782-11e5-82fb-21f484115125.png)

**Comment by jrgryph** [comment]
Same here... in the Minecraft logs I get [Client thread/WARN]: Failed to load texture: Simukraft:races/Dark Elf/female/female189.png as an example. I bunch more from other skins as well.

**Comment by BossKaiden** [comment]
Same with me.

**Comment by xXXIMMATTHEWXXx** [comment]
Hello! I am porting this port to try and update the inactivity from the person who updated this mod. Please [recreate the issue here.](https://github.com/xXXIMMATTHEWXXx/Sim-u-kraft-Restored)

**Comment by ashjack** [comment]
Please download and install Resource Loader, if you don't use this mod, skins will not show up
