### ISSUE TITLE
Crashes and Skin Corruption 

### ISSUE THREAD

**Issue by BossKaiden** [ashjack/Sim-U-Kraft-Reloaded#80]
The skins are purple and Black.
 Also, I get error:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 8/15/16 3:56 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(Unknown Source)
    at java.util.HashMap$KeyIterator.next(Unknown Source)
    at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:269)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:648)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (x86) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 113254440 bytes (108 MB) / 362070016 bytes (345 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 4 mods loaded, 4 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   ashjacksimukraftreloaded{1.0.4a} [Sim-U-Kraft Reloaded](Sim-U-Kraft Reloaded - 1.0.4a.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['BossKaiden'/386, l='Sim-U-Craft MOD', x=-342.83, y=5.00, z=-600.26]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by AwesomeDonut67** [comment]
Did you download resourceloader 1.2? And try restarting your computer I had the same issue and it worked when I restarted my computer.

**Comment by BossKaiden** [comment]
what is resource loader 1.2?

**Comment by xXXIMMATTHEWXXx** [comment]
Hello! I am porting this port to try and update the inactivity from the person who updated this mod. Please [recreate the issue here.](https://github.com/xXXIMMATTHEWXXx/Sim-u-kraft-Restored)
