### ISSUE TITLE
Sim skins not working

### ISSUE THREAD

**Issue by thespotdog** [ashjack/Sim-U-Kraft-Reloaded#85]
I know that this mod was made for 1.7.10, and I dont know if anyone will read this but i have a problem with the mod. Everything works find BUT the sims skins. When I go in game, the skins are just black and pink, like a glitch block. I really enjoy this game and I really need help!

**Comment by ashjack** [comment]
This is because you have not followed the installation instructions properly. Please install Resource Loader and ensure you have put the 'Resources' folder provided with Sim-U-Kraft Reloaded in the .minecraft folder
