### ISSUE TITLE
/generatefolk error

### ISSUE THREAD

**Issue by Matthewj555** [ashjack/Sim-U-Kraft-Reloaded#87]
When I try to use it, the game says "An unknown error occurred while attempting to preform this command"
Help would be greatly appreciated!

**Comment by ashjack** [comment]
Please can you provide a log of this error occurring? I can't seem to reproduce the error on my side.

**Comment by Matthewj555** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Please disregard, error seems to have resolved itself.  Thank you.


Sent from Yahoo Mail for iPhone


On Saturday, June 24, 2017, 5:23 PM, ashjack <notifications@github.com> wrote:


Please can you provide a log of this error occurring? I can't seem to reproduce the error on my side.

**Comment by ashjack** [comment]
Okay, no worries
